import { Trip } from "./types";

export const mockTrip: Trip = {
  id: "trip-tokyo-2026",
  name: "Tokyo Adventure",
  destination: "Tokyo, Japan",
  startDate: "2026-04-15",
  endDate: "2026-04-22",
  heroImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600&q=80",
  participants: [
    { id: "p1", name: "Alex", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex", role: "organizer" },
    { id: "p2", name: "Jordan", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan", role: "member" },
    { id: "p3", name: "Sam", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sam", role: "member" },
    { id: "p4", name: "Taylor", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor", role: "member" },
  ],
  itinerary: [
    {
      date: "2026-04-15",
      dayNumber: 1,
      venues: [
        {
          id: "v1",
          name: "Senso-ji Temple",
          type: "sight",
          time: "09:00",
          endTime: "11:00",
          description: "Tokyo's oldest and most significant temple, located in Asakusa.",
          address: "2-3-1 Asakusa, Taito City, Tokyo",
          imageUrl: "https://images.unsplash.com/photo-1583766395091-2eb9994ed094?w=400&q=80",
          lat: 35.7148,
          lng: 139.7967,
          rating: 4.7,
        },
        {
          id: "v2",
          name: "Ichiran Ramen",
          type: "restaurant",
          time: "12:00",
          endTime: "13:00",
          description: "Famous solo-dining ramen experience with rich tonkotsu broth.",
          address: "1-22-7 Jinnan, Shibuya, Tokyo",
          imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80",
          lat: 35.6614,
          lng: 139.6993,
          rating: 4.5,
          priceLevel: 2,
        },
        {
          id: "v3",
          name: "teamLab Borderless",
          type: "activity",
          time: "14:30",
          endTime: "17:00",
          description: "Immersive digital art museum with stunning interactive exhibits.",
          address: "Azabudai Hills, Minato City, Tokyo",
          imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400&q=80",
          lat: 35.6585,
          lng: 139.7454,
          rating: 4.8,
          priceLevel: 3,
        },
      ],
    },
    {
      date: "2026-04-16",
      dayNumber: 2,
      venues: [
        {
          id: "v4",
          name: "Tsukiji Outer Market",
          type: "restaurant",
          time: "08:00",
          endTime: "10:00",
          description: "Fresh sushi breakfast and street food at Tokyo's famous fish market.",
          address: "4-16-2 Tsukiji, Chuo City, Tokyo",
          imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=400&q=80",
          lat: 35.6654,
          lng: 139.7707,
          rating: 4.6,
          priceLevel: 2,
        },
        {
          id: "v5",
          name: "Meiji Jingu Shrine",
          type: "sight",
          time: "11:00",
          endTime: "12:30",
          description: "Serene Shinto shrine surrounded by a lush forest in the heart of Tokyo.",
          address: "1-1 Yoyogikamizonocho, Shibuya, Tokyo",
          imageUrl: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=400&q=80",
          lat: 35.6764,
          lng: 139.6993,
          rating: 4.7,
        },
        {
          id: "v6",
          name: "Shibuya Crossing & Shopping",
          type: "activity",
          time: "14:00",
          endTime: "17:00",
          description: "Experience the world's busiest crossing and explore Shibuya's shops.",
          address: "Shibuya Crossing, Shibuya, Tokyo",
          imageUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=400&q=80",
          lat: 35.6595,
          lng: 139.7004,
          rating: 4.4,
        },
      ],
    },
    {
      date: "2026-04-17",
      dayNumber: 3,
      venues: [
        {
          id: "v7",
          name: "Mount Fuji Day Trip",
          type: "activity",
          time: "07:00",
          endTime: "18:00",
          description: "Full-day excursion to Japan's iconic mountain with stops at Lake Kawaguchi.",
          address: "Fuji-Hakone-Izu National Park",
          imageUrl: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=400&q=80",
          lat: 35.3606,
          lng: 138.7274,
          rating: 4.9,
          priceLevel: 3,
        },
      ],
    },
  ],
  polls: [
    {
      id: "poll1",
      question: "Where should we have dinner on Day 2?",
      status: "active",
      totalVotes: 3,
      createdAt: "2026-04-10T10:00:00Z",
      closesAt: "2026-04-14T23:59:00Z",
      options: [
        { id: "opt1", text: "Gonpachi (Kill Bill restaurant)", votes: 2, voters: ["p1", "p3"], imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=200&q=80" },
        { id: "opt2", text: "Robot Restaurant", votes: 1, voters: ["p2"], imageUrl: "https://images.unsplash.com/photo-1554797589-7241bb691973?w=200&q=80" },
        { id: "opt3", text: "Yakitori Alley, Yurakucho", votes: 0, voters: [] },
      ],
    },
    {
      id: "poll2",
      question: "Day trip preference?",
      status: "closed",
      totalVotes: 4,
      createdAt: "2026-04-08T10:00:00Z",
      options: [
        { id: "opt4", text: "Mount Fuji & Lake Kawaguchi", votes: 3, voters: ["p1", "p2", "p4"] },
        { id: "opt5", text: "Kamakura & Great Buddha", votes: 1, voters: ["p3"] },
      ],
    },
  ],
  preferences: {
    pace: 3.5,
    budget: 3,
    adventure: 4,
    culture: 4.5,
    food: 5,
    nightlife: 2.5,
  },
  actionItems: [
    { id: "a1", text: "Book teamLab tickets", assignee: "Alex", completed: true },
    { id: "a2", text: "Reserve dinner for Day 2", assignee: "Jordan", completed: false },
    { id: "a3", text: "Get Suica cards at airport", completed: false },
    { id: "a4", text: "Share hotel WiFi password", assignee: "Sam", completed: true },
  ],
};
